name: swan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - pandas==1.5.3
    - python=3.8.0
    - jupyterlab=4.0.3
    - scanpy==1.9.3
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - numpy=1.24.4
